sudo: false
dist: trusty

addons:
  apt:
    packages:
      - tidy
      - tcl
      - tk

install: bundle install --without=benchmark

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.3
  - 2.4.0
  - rbx-3.69
  - ruby-head

notifications:
  email: false
